[workspace]
members = [
    "ch001-hello",
    "ch011-vector",
    "ch012-hashmap-hashset",
    "ch013-iterator",
    "ch014-time-chrono",
    "ch015-thread",
    "ch016-scope-thread"]

resolver = "3"
